# Generated by Django 4.2.1 on 2023-05-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podio',
            name='tipo_podio',
            field=models.CharField(choices=[('Podio Niño', 'Pn'), ('Podio Persona', 'Pp'), ('Podio Empresa', 'Pe'), ('Podio Internacional', 'Pi')], max_length=50, null=True),
        ),
    ]
