# Generated by Django 4.1.7 on 2023-04-04 23:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('numero_documento', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=12, null=True)),
                ('foto', models.ImageField(max_length=255, null=True, upload_to='image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('tipo_documento', models.CharField(choices=[('Cédula de Ciudadanía', 'Cc'), ('Registro Civil', 'Rc'), ('Tarjeta de Identidad', 'Ti'), ('Cédula de Extranjería', 'Ce'), ('Número de Identificación Tributaria', 'Nit')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.CharField(max_length=150)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Niño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.persona')),
            ],
        ),
    ]
