# Generated by Django 4.1.7 on 2023-04-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0002_alter_persona_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='estado',
            field=models.BooleanField(default=0),
        ),
    ]
